[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "OpenSSL",
]

unused-allowed-license = "warn"
confidence-threshold = 0.95

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = []
