services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: brawl
      POSTGRES_PASSWORD: brawl
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
