name: Security audit
on:
  push:
    branches-ignore:
<<<<<<< HEAD
      - 'automation/**'
=======
      - 'automation/brawl/temp/*'
>>>>>>> 685dabf (ignore tmp branch)
    paths:
      - '.github/workflows/audit.yaml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "stable"
